on:
  push:
    branches:
    - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: "go test -v -race -coverprofile=coverage.txt -covermode=atomic ./..." 
    - uses: codecov/codecov-action@v1
