on:
  push:
    branches:
    - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: "go test -v -race -coverprofile=coverage.out -covermode=atomic ./..."
    - run: "go tool cover -func=coverage.out -o coverage.txt" 
    - uses: codecov/codecov-action@v1
